# Generated by Django 4.2.5 on 2023-09-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="studentDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=10)),
                ("second_name", models.CharField(max_length=10)),
                ("job", models.IntegerField()),
                ("salary", models.IntegerField()),
            ],
        ),
    ]
